version: '3.8'

networks:
  backup-network:
    driver: bridge

services:
  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - backup-network

  backend:
    build: ./backend
    environment:
      CLICKHOUSE_URL: "http://clickhouse:8123"
      BACKUP_STORAGE: "/backups"
      CLICKHOUSE_HOST: "clickhouse"
      CLICKHOUSE_PORT: "9000"
      CLICKHOUSE_USER: "admin"
      CLICKHOUSE_PASSWORD: "password"
      CLICKHOUSE_DB: "mydb"
      DEBUG: "true"
    volumes:
      - backup_volume:/backups
    depends_on:
      - clickhouse
    networks:
      - backup-network

  clickhouse:
    image: clickhouse/clickhouse-server:25.5.5.19-alpine
    ports:
      - "8123:8123"
      - 9000:9000
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - backup_volume:/backups
      - ./backup_disk.xml:/etc/clickhouse-server/config.d/backup_disk.xml
    environment:
      CLICKHOUSE_DB: "mydb"
      CLICKHOUSE_USER: "admin"
      CLICKHOUSE_PASSWORD: "password"
    networks:
      - backup-network

volumes:
  clickhouse_data:
  backup_volume:
